Several pretty minor edits after I read through this doc.
ietf-wg-gnap/gnap-resource-servers pull request #38
Opened 2021-07-13 18:24 UTC by adeinega

2021-07-13 19:48 UTC, jricher requested changes
Thanks for the read through! It's appreciated. A couple comments on this, and marking it editorial for when we pull it in.

2021-07-13 19:48 UTC, jricher commented on draft-ietf-gnap-resource-servers.md
> +protocol neither makes assumptions nor demands on the format or contents
```suggestion
protocol makes neither assumptions nor demands on the format or contents
```

2021-07-13 19:48 UTC, jricher commented on draft-ietf-gnap-resource-servers.md
> + - has not been expired
Reverting as "expiration" is usually a passive action based on a timeout.

```suggestion
 - has not expired
```

2021-07-13 19:48 UTC, jricher commented on draft-ietf-gnap-resource-servers.md
> +the access token to the client instance, and the means of the client instance
Only two items here, no comma needed.

```suggestion
the access token to the client instance and the means of the client instance
```

2021-07-13 21:50 UTC, adeinega commented
A couple of other minor things

> key (object/string): : REQUIRED if the token is bound. The key bound to the access token, to allow the RS to validate the signature of the request from the client instance. If the access token is a bearer token, this MUST NOT be included.

it sounds to me like an optional step for the RS to validate the signature if the key object is presented in the introspection response. That should be MUST, right?

The third step in section "Token Introspection" states that

> The AS validates the access token value and the Resource Server's request and returns the introspection response for the token.

I think that the AS should validate the RS's request and only after that the AT's value.

2021-07-14 16:14 UTC, jricher commented
The RS always has to validate the signature, but sometimes it can't fully validate it until after it looks up the token's data using introspection. We should look at what OAuth MTLS and DPoP say in terms of RS validation steps.

The intent of the language for the AS validation was not to imply an order in either direction, so we can look to tweak this to make that more clear.

2021-07-16 15:42 UTC, jricher approved these changes

2021-07-21 15:52 UTC, merged